# Generated by Django 5.2.5 on 2025-09-15 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Produk')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Produk')),
                ('price', models.IntegerField(verbose_name='Harga Produk')),
                ('description', models.TextField(verbose_name='Deskripsi Produk')),
                ('thumbnail', models.URLField(verbose_name='URL Thumbnail Produk')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Produk Unggulan')),
                ('is_available', models.BooleanField(default=True, verbose_name='Ketersediaan Produk')),
                ('category', models.CharField(max_length=20, verbose_name='Kategori Produk')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
            },
        ),
    ]
